### ISSUE TITLE
[Feature request] Props

### ISSUE THREAD

**Issue by abedi0** [NatiqQuran/yakad#10] opened 2023-01-12 18:15 UTC
# Add a required prop for inputField
Some forms have a required input, so the user must pass the data, which is required in the backend, so the backend wants some data strictly.

**Comment by ekiuse** [comment] 2023-01-30 12:01
In update 1.2.31-beta, the problem is fixed

**Comment by AzerothA** [comment] 2023-01-31 10:06
Its need to fixed in the main repo. Please link the PR for this issue.

**Closed** 2024-06-15 12:17 UTC
Labels: enhancement
